# Deploy java app on production
---
- hosts: 10.0.0.8
  become: yes
  tasks:
    - name: Deploy Java App on Production
      get_url:
        url: http://172.174.80.38:8082/artifactory/mySIT-Repo/com/maha/VamsiLogin/2.0/VamsiLogin-2.0.war
        dest: /opt/tomcat/webapps/login.war
        force_basic_auth: yes
        url_username: admin
        url_password: Login@3203

    - name: Download tar file
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest: /home/vamsiuser/apache-tomcat-10.0.20.tar.gz
        force_basic_auth: yes

    - name: Extract tar file
      command: 
        cmd: sudo tar xzf /home/vamsiuser/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
        creates: /opt/tomcat/LICENSE
